services:
  claude-code-persistent:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
        NODE_VERSION: "23"
        PYTHON_VERSION: "3.12"
        AWS_CLI_VERSION: "2.15.0"
        CLAUDE_CODE_VERSION: "latest"
    container_name: claude-code-persistent
    user: node
    working_dir: /projects
    group_add:
      - ${DOCKER_GID:-996}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - claude-code-bashhistory:/commandhistory
      - claude-code-config:/home/node/.claude
      - ${HOME}/Projects:/projects:cached
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/node/.claude
      - POWERLEVEL9K_DISABLE_GITSTATUS=true
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - GITLAB_PERSONAL_ACCESS_TOKEN=${GITLAB_PERSONAL_ACCESS_TOKEN}
      - GITLAB_API_URL=${GITLAB_API_URL:-https://gitlab.com/api/v4}
      - GITLAB_READ_ONLY_MODE=${GITLAB_READ_ONLY_MODE:-false}
      - PLAYWRIGHT_BROWSERS_PATH=/usr/local/share/playwright-browsers
    command: sleep infinity
    stdin_open: true
    tty: true

volumes:
  claude-code-bashhistory:
  claude-code-config: